---
title: "Урок двадцать третий: Основы Shiny: ui и server, input и output"
author: "Вячеслав Арбузов"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

## Синтаксис на демо примерах
Посмотрим разнообразные демо примеры

```{r}
library(shiny)
runExample()

# Run one of the examples
# runExample("01_hello")
# runExample('06_tabsets')
# runExample('09_upload')
# runExample('11_timer')

```


## Визуальное создание UI

```{r}
#install.packages("remotes")
#remotes::install_github("rstudio/shinyuieditor")
library(shinyuieditor)
#shinyuieditor::launch_editor(app_loc = "new-app/")

```
## Простой веб сервис

```{r}

# shiny simple

library(shiny)

ui <- fluidPage(
  sliderInput("x", "If x is", min = 1, max = 50, value = 30),
  sliderInput("y", "and y is", min = 1, max = 50, value = 5),
  "then, (x * y) is", textOutput("product"),
  "and, (x * y) + 5 is", textOutput("product_plus5"),
  "and (x * y) + 10 is", textOutput("product_plus10")
)

server <- function(input, output, session) {
  output$product <- renderText({ 
    product <- input$x * input$y
    product
  })
  output$product_plus5 <- renderText({ 
    product <- input$x * input$y
    product + 5
  })
  output$product_plus10 <- renderText({ 
    product <- input$x * input$y
    product + 10
  })
}

#shinyApp(ui, server)
```


## Используем дополнительные Shiny темы

```{r}

library(shiny)
library(shinythemes)

# Define UI for app that draws a histogram ----
ui <- fluidPage(
  theme = shinytheme("cosmo"),
  # App title ----
  titlePanel("Hello Shiny!"),
  
  # Sidebar layout with input and output definitions ----
  sidebarLayout(
    
    # Sidebar panel for inputs ----
    sidebarPanel(
      
      # Input: Slider for the number of bins ----
      sliderInput(inputId = "bins",
                  label = "Number of bins:",
                  min = 1,
                  max = 50,
                  value = 30)
      
    ),
    
    # Main panel for displaying outputs ----
    mainPanel(
      
      # Output: Histogram ----
      plotOutput(outputId = "distPlot")

    )
  )
)

# Define server logic required to draw a histogram ----
server <- function(input, output) {
  
  # Histogram of the Old Faithful Geyser Data ----
  # with requested number of bins
  # This expression that generates a histogram is wrapped in a call
  # to renderPlot to indicate that:
  #
  # 1. It is "reactive" and therefore should be automatically
  #    re-executed when inputs (input$bins) change
  # 2. Its output type is a plot
  output$distPlot <- renderPlot({
    
    x    <- faithful$waiting
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    hist(x, breaks = bins, col = "#75AADB", border = "white",
         xlab = "Waiting time to next eruption (in mins)",
         main = "Histogram of waiting times")
    
  })
  
}

#shinyApp(ui = ui, server = server)

```


